name: dailymotiv
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"  # Changed to a more compatible range

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  url_launcher: ^6.1.0  # For sharing quotes
  fluttertoast: ^8.2.0  # For toast messages
  provider: ^6.1.1   
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  build_runner: ^2.4.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/silhouette_peak.png